# Generated by Django 5.2.13 on 2026-04-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='current_round',
            field=models.CharField(default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='democonfig',
            name='default_jd_text',
            field=models.TextField(default='Default Job Description for interviews.'),
        ),
    ]
