# Generated by Django 5.2.13 on 2026-04-17 10:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0002_customuser_current_round_democonfig_default_jd_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('difficulty', models.CharField(default='medium', max_length=50)),
                ('round_type', models.CharField(default='technical', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
            ],
        ),
    ]
