# Generated by Django 5.2.13 on 2026-04-17 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0003_interviewinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='active_invitation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot_app.interviewinvitation'),
        ),
        migrations.AddField(
            model_name='interviewinvitation',
            name='jd_file',
            field=models.FileField(blank=True, null=True, upload_to='invitation_jds/'),
        ),
    ]
