# Generated by Django 5.2.13 on 2026-04-19 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0005_interviewreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='democonfig',
            name='demo_is_paid',
        ),
        migrations.RemoveField(
            model_name='democonfig',
            name='demo_price_cents',
        ),
    ]
